github.com:
    users:
        XNeyMo:
            oauth_token: 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
    git_protocol: https
    user: XNeyMo
    oauth_token: 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
