github.com:
    users:
        XNeyMo:
            oauth_token: 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
    git_protocol: ssh
    user: XNeyMo
    oauth_token: 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
