github.com:
    users:
        XNeyMo:
            oauth_token: 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
    git_protocol: ssh
    user: XNeyMo
    oauth_token: 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
