#! /bin/sh
#====================================================================
#
#
#	██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#	██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#	██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#	██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#	██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#	╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#
#
#	Author: XNeyMo
#	GitHub: https://github.com/XNeyMo/dotfiles
#
#
#====================================================================

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d '  一  ' '二  ' '三  ' '四  ' '五  ' '六  '

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

wallset --set --add ~/.wallpapers/atomic.png

sxhkd -c ~/.config/bspwm/sxhkdrc &
polybar &
