#!/usr/bin/env bash
#
#   ██████╗ ██████╗ ██╗ ██████╗ ██╗  ██╗████████╗███╗   ██╗███████╗███████╗███████╗
#   ██╔══██╗██╔══██╗██║██╔════╝ ██║  ██║╚══██╔══╝████╗  ██║██╔════╝██╔════╝██╔════╝
#   ██████╔╝██████╔╝██║██║  ███╗███████║   ██║   ██╔██╗ ██║█████╗  ███████╗███████╗
#   ██╔══██╗██╔══██╗██║██║   ██║██╔══██║   ██║   ██║╚██╗██║██╔══╝  ╚════██║╚════██║
#   ██████╔╝██║  ██║██║╚██████╔╝██║  ██║   ██║   ██║ ╚████║███████╗███████║███████║
#   ╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝╚══════╝╚══════╝╚══════╝
#
#       Author - rxyhn
#       GitHub - https://github.com/rxyhn/tokyo
#

ASSETS="$HOME/.config/bspwm/assets"
STEPS=5

function get_brightness {
	brightnessctl i | grep -oP '\(\K[^%\)]+'
}

function send_notification {
	icon="$ASSETS/brightness.svg"
	brightness=$(get_brightness)
	dunstify "Brightness $brightness%" -i $icon -r 5555 -u normal
}

case $1 in
	up)
		brightnessctl set "${STEPS:-5}%+" -q
		send_notification
		;;
	down)
		brightnessctl set "${STEPS:-5}%-" -q
		send_notification
		;;
esac
