#!/usr/bin/env bash
#
#    ██████╗ ██████╗ ███████╗███╗   ██╗ █████╗ ██████╗ ██████╗ ███████╗
#   ██╔═══██╗██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔══██╗██╔══██╗██╔════╝
#   ██║   ██║██████╔╝█████╗  ██╔██╗ ██║███████║██████╔╝██████╔╝███████╗
#   ██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║██╔══██║██╔═══╝ ██╔═══╝ ╚════██║
#   ╚██████╔╝██║     ███████╗██║ ╚████║██║  ██║██║     ██║     ███████║
#    ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝
#
#       Author - XNeyMo
#       GitHub - https://github.com/xneymo/dotfiles
#

case "$1" in
    --terminal)
        alacritty
        ;;
    --fm)
	      thunar
	      ;;
    --browser)
        firefox
        ;;
    --telegram)
        telegram-desktop
        ;;
    --whats)
        zapzap
        ;;
    --discord)
        discord
        ;;
    --notes)
	      obsidian
	      ;;
    --office)
	      wps
	      ;;
    *)
        echo "Invalid Option"
        ;;
esac
