#!/usr/bin/env bash
#
#   ███████╗ ██████╗██████╗ ███████╗███████╗███╗   ██╗███████╗██╗  ██╗ ██████╗ ████████╗███████╗██████╗ 
#   ██╔════╝██╔════╝██╔══██╗██╔════╝██╔════╝████╗  ██║██╔════╝██║  ██║██╔═══██╗╚══██╔══╝██╔════╝██╔══██╗
#   ███████╗██║     ██████╔╝█████╗  █████╗  ██╔██╗ ██║███████╗███████║██║   ██║   ██║   █████╗  ██████╔╝
#   ╚════██║██║     ██╔══██╗██╔══╝  ██╔══╝  ██║╚██╗██║╚════██║██╔══██║██║   ██║   ██║   ██╔══╝  ██╔══██╗
#   ███████║╚██████╗██║  ██║███████╗███████╗██║ ╚████║███████║██║  ██║╚██████╔╝   ██║   ███████╗██║  ██║
#   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚══════╝╚═╝  ╚═╝
#
#       Author - gh0stzk
#       GitHub - https://github.com/gh0stzk/dotfiles
#

timestamp=$(date +%Y-%m-%d-%I%M%S)
dir="$HOME/Pictures/ScreenShots"
filename="$dir/Shot-${timestamp}.png"
[ -d "$dir" ] || mkdir -p "$dir"

show_notification() {
    if [[ -e "$filename" ]]; then
        dunstify --replace=699 -i "Screenshot Save" "Screenshot Saved"
    else
        dunstify --replace=699 -i custom-trash-bin "Screenshot" "Screenshot Canceled"
    fi
}

take_screenshot() {
    maim -u "$@" "$filename"
    xclip -selection clipboard -t image/png -i "$filename"
    show_notification
}

countdown() {
    for sec in $(seq "$1" -1 1); do
        dunstify -t 1000 --replace=699 -i  ~/.config/bspwm/assets/screenshot.svg "Taking shot in : $sec"
        sleep 1
    done
}

case $1 in
    --now)
        take_screenshot ;;
    --in10)
        countdown 10 && take_screenshot ;;
    --sel)
        take_screenshot -s -o ;;
    --active)
        take_screenshot -i "$(xdotool getactivewindow)" ;;
    *)
        take_screenshot ;;
esac
