#=============================================================================
#
#
#	 █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#	██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#	███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝ 
#	██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝  
#	██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║   
#	╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝   
#
#
#	Author: XNeyMo
#	GitHub: https://github.com/XNeyMo/dotfiles/
#
#
#=============================================================================

import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[window.padding]
x = 15
y = 15

[window]
dynamic_padding = true
