#
#    █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#   ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#   ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝ 
#   ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝  
#   ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║   
#   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝   
#
#       Author - XNeyMo
#       GitHub - https://github.com/xneymo/dotfiles
#

import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

[cursor]
blink_interval = 500
unfocused_hollow = false

[cursor.style]
blinking = "On"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 15
y = 15
