#=========================================================
#
#
#	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
#	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
#	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
#	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
#	╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
#	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
#
#
#	Author - XNeyMo
#	GitHub - https://github.com/xneymo/dotfiles
#
#
#=========================================================

[colors.primary]
background = "#0b0419"
foreground = "#e6e2d7"

[colors.cursor]
cursor = "#e6e2d7"
text = "#0b0419"

[colors.normal]
black = "#1a0f2c"
blue = "#1f3a93"
cyan = "#0d5e6d"
green = "#1a7f37"
magenta = "#6c2c70"
red = "#a61d4c"
white = "#ffffff"
yellow = "#b58900"

[colors.bright]
black = "#4d4d4d"
blue = "#4d4dff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"
