#=================================================
#
#
#	███████╗ ██████╗ ███╗   ██╗████████╗
#	██╔════╝██╔═══██╗████╗  ██║╚══██╔══╝
#	█████╗  ██║   ██║██╔██╗ ██║   ██║   
#	██╔══╝  ██║   ██║██║╚██╗██║   ██║   
#	██║     ╚██████╔╝██║ ╚████║   ██║   
#	╚═╝      ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   
#
#
#	Author: XNeyMo
#	GitHub: https://github.com/XNeyMo/dotfiles
#
#
#=================================================

[font]
size = 10
