;==============================================================
;
;
;	██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;	██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;	██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;	██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;	██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;	╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;	Author: XNeyMo
;	GitHub: https://github.com/XNeyMo/dotfiles
;
;
;==============================================================

[global/wm]
margin-bottom = 0pt
margin-top = 0pt
include-file = modules.ini
include-file = colors.ini

[bar/example]
width = 90%
height = 24pt

offset-x = 5%

radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 4pt
border-color = ${colors.trasnparent}

padding = 2

module-margin = 0

separator = 
dim-value = 1.0

font-0 = monospace;2

modules-left = memory cpu
modules-center = xworkspaces
modules-right = pulseaudio date

cursor-click = pointer
cursor-scroll =

enable-ipc = true
wm-restack = bspwm

[Settings]
screenchange-reload = true
pseudo-transparency = true
