;==============================================================
;
;
;	██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;	██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;	██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;	██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;	██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;	╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;	Author: XNeyMo
;	GitHub: https://github.com/XNeyMo/dotfiles
;
;
;==============================================================

[global/wm]
margin-bottom = 0
margin-top = 0
include-file = modules.ini
include-file = colors.ini

[bar/example]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 90%
height = 26

offset-x = 5%
offset-y = 10

background = ${colors.background}
foreground = ${colors.foreground}

radius = 4.0

line-size = 2
line-color = ${colors.blue}

border-size = 8px
border-color = ${colors.background}

padding = 1

module-margin-left = 0
module-margin-right = 0

font-0 = "Noto Sans JP:style=Bold:pixelsize=10;2"
font-1 = "SymbolsNerdFont;2"

;Modules availables but not active: 
;	battery		brightness		weather
modules-left = bl cpu br sep bl memory br
modules-center = bl bspwm br
modules-right = date

separator =
dim-value = 1.0

;;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer 
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
